/*
 * global.h
 *
 *  Created on: Mar 20, 2013
 *      Author: cvora
 */

#ifndef GLOBAL_H_
#define GLOBAL_H_

#include "synch.h"

typedef struct _ItemInfo
{
	/**
	 * Price of the item
	 */
	int 	Price;
	/**
	 * Shelf where the item is placed
	 */
	int 	shelfNo;
	/**
	 * Department No where item is from
	 */
	int 	departmentNo;
	/**
	 * Total number of item Type in stock
	 */
	int		noOfItems;
}ItemInfo;


typedef struct _CustomerShoppingList
{
	/**
	 * Item No to shop
	 */
	int 	 itemNo;
	/**
	 * No (Quantity) of items of that Item No above to shop
	 */
	int		 noOfItems;
}CustomerShoppingList;

typedef enum _CustomerType
{
	PRIVILEGED = 0,
	NON_PRIVILEGED
}CustomerType;

typedef struct _CustomerInfo
{
	/**
	 * Type of Customer - Privileged or Non Privileged
	 */
	CustomerType 			type;
	/**
	 * Money Customer can spend for shopping
	 */
	int 					money;
	/**
	 * Shopping List Item Count
	 */
	int						noOfItems;
	/**
	 * has enough money for shopping or no
	 */
	bool					hasEnoughMoneyForShopping;
	/**
	 * is done shopping or not
	 */
	bool					isDoneShopping;
	/**
	 * Shopping List for Customer
	 */
	CustomerShoppingList	*pCustomerShoppingList;
}CustomerInfo;


typedef enum _SalesManStatus
{
	salesmanIsFree = 0,
	salesmanIsBusy,
	salesmanSignalToCustomerFromDeptWaitQueue,
	salesmanSignalToCustomerFromDeptComplainWaitQueue
}SalesManStatus;

typedef struct _SalesManInfo
{
	/**
	 * If the Salesman is free or busy handling customer or just signaled a Customer
	 */
	SalesManStatus status;
	/**
	 *
	 */
	/**
	 * Department Salesman is working for
	 */
	int	 departmentNo;
	/**
	 * Customer Salesman is handling or will be handling in future
	 */
	int customerId;
	/**
	 * item to be re stocked
	 */
	int itemToRestock;
}SalesManInfo;

typedef enum _GoodLoaderStatus
{
	goodLoaderIsFree = 0,
	goodLoaderIsBusy,
	goodLoaderSignalToSalesman
}GoodLoaderStatus;

typedef struct _GoodLoaderInfo
{
	/**
	 * If the Good Loader is free or busy handling salesman
	 */
	GoodLoaderStatus status;
	/**
	 * Salesman Good Loader is handling or will be handling in future.
	 */
	int salesmanId;
	/**
	 * item to be re stocked
	 */
	int itemToRestock;
}GoodLoaderInfo;

typedef enum _CashierStatus
{
	cashierIsFree = 0,
	cashierIsBusy,
	cashierSignalToCustomer
}CashierStatus;

typedef struct _CashierInfo
{
	/*
	 * Status of cashier
	 */
	CashierStatus	status;
	/**
	 * Customer Cashier is handling or will be handling in future
	 */
	int 			customerId;
	/**
	 * bill of current Customer
	 */
	int 			bill;
	/**
	 * total sales collection
	 */
	int 			totalSalesMoney;
}CashierInfo;

typedef struct _ManagerInfo
{
	/**
	 * Cashier Manager is handling or will be handling in future
	 */
	int 			cashierId;
	/**
	 * Customer Manager is handling or will be handling in future
	 */
	int 			customerId;
	/**
	 * Customer's bill to negotiate
	 */
	int 			customerBill;
	/**
	 * Total revenue generated by store as of now
	 */
	int				totalRevenue;
}ManagerInfo;

/**
 * extern tells the compiler this variable is declared elsewhere
 */
extern ItemInfo 		g_itemInfo[NO_OF_ITEM_TYPES];

extern CustomerInfo 	g_customerInfo[NO_OF_CUSTOMERS];

extern SalesManInfo 	g_salesmanInfo[NO_OF_SALESMAN];

extern GoodLoaderInfo 	g_goodLoaderInfo[NO_OF_GOOD_LOADERS];

extern CashierInfo		g_cashierInfo[NO_OF_CASHIERS];

extern ManagerInfo		g_managerInfo;

/**
 * Number of customer served and left
 */
extern int g_noOfCustomersLeft;
extern int simulationEnd;

/**
 * Locks, Condition Variables, Queue Wait Count for Customer-Trolley interaction
 */
extern int 			g_usedTrolleyCount;
extern int 			g_waitForTrolleyCount;
extern Lock* 		g_customerTrolleyLock;
extern Condition* 	g_customerTrolleyCV;

/**
 * Locks, Condition Variables for Customer-Salesman interaction
 */
extern Lock*		g_customerSalesmanLock[NO_OF_SALESMAN];
extern Condition*  	g_customerSalesmanCV[NO_OF_SALESMAN];

/**
 * Locks,Condition Variables and Queue Length for Customer-Department Interaction
 */
extern Lock*		g_customerDepartmentLock[NO_OF_DEPARTMENT];
extern Condition*	g_customerDepartmentCV[NO_OF_DEPARTMENT];
extern int			g_departmentWaitQueue[NO_OF_DEPARTMENT];

/**
 * Locks for accessing items on the shelf
 */
extern Lock*		g_shelfAccessLock[NO_OF_SHELFS];

/**
 * Locks,Condition Variables and Queue Length for Customer-Department Interaction
 */
extern Lock*		g_customerDepartmentComplainLock[NO_OF_DEPARTMENT];
extern Condition*	g_customerDepartmentComplainCV[NO_OF_DEPARTMENT];
extern int			g_departmentComplainWaitQueue[NO_OF_DEPARTMENT];

/**
 * Locks,Condition Variables and Queue Length for Salesman - GoodsLoader Interaction
 */
extern Lock*		g_salesmanGoodsLoaderLock[NO_OF_GOOD_LOADERS];
extern Condition*  	g_salesmanGoodsLoaderCV[NO_OF_GOOD_LOADERS];

extern Lock*		g_goodLoaderWaitLock[NO_OF_GOODLOADER_WAIT_QUEUE];
extern Condition*	g_goodLoaderWaitCV[NO_OF_GOODLOADER_WAIT_QUEUE];
extern int			g_goodLoaderWaitQueue[NO_OF_GOODLOADER_WAIT_QUEUE];

/**
 * Locks,Condition Variables and Queue Length for Customer - Cashier Interaction
 */
extern Lock*		g_cashierLineLock[NO_OF_CASHIERS];
extern Condition*	g_cashierLineCV[NO_OF_CASHIERS];
extern int			g_cashierWaitQueue[NO_OF_CASHIERS];

extern Lock*		g_cashierPrivilegedLineLock[NO_OF_CASHIERS];
extern Condition*  	g_cashierPrivilegedLineCV[NO_OF_CASHIERS];
extern int			g_cashierPrivilegedWaitQueue[NO_OF_CASHIERS];

extern Lock*		g_customerCashierLock[NO_OF_CASHIERS];
extern Condition*	g_customerCashierCV[NO_OF_CASHIERS];

/**
 * Locks, Condition Variables and Queue Length for Manager - Cashier  Cash Collection Interaction
 */
extern Lock*		g_managerCashierCashLock[NO_OF_CASHIERS];

/**
 * Locks, Condition Variables and Queue Length for Manager Interaction
 */

extern Lock*		g_managerCashierLock;
extern Condition*	g_managerCashierCV;
extern int			g_managerWaitQueueLength;

extern Lock*		g_managerCashierInteractionLock;
extern Condition*	g_managerCashierInteractionCV;

/**
 * Locks, Condition Variables for Manager - Customer Interaction
 */
extern Lock*		g_managerCustomerInteractionLock;
extern Condition*	g_managerCustomerInteractionCV;

/*************************************GLOBAL DATA STRUCTS DECLARATION**********************************************/


#endif /* GLOBAL_H_ */
